import { useColors, useTheme } from "@/contexts/ThemeContext";
import React, { useState, useEffect, useMemo, useCallback, useRef } from "react";
import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  Platform,
  ActivityIndicator,
  TextInput,
  useWindowDimensions,
  ScrollView,
  BackHandler,
  Animated,
} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import Constants from "expo-constants";
import { 
  ArrowLeft, 
  Search, 
  Book, 
  BookOpen, 
  ChevronRight, 
  X,
  Volume2,
  Info,
  Hash,
  Play,
  RotateCcw,
  Sparkles,
  CheckCircle2,
  Trophy,
  Languages,
  Check,
  PlusCircle,
  FilePlus,
  AlertCircle,
  Award
} from "lucide-react-native";
import { 
  getLearningPaths, 
  getModules, 
  getLessons, 
  saveNote, 
  getCourseDictionary,
  generateId,
  type DictEntry
} from "@/utils/storage";
import { tokenizeJapanese, lookupWord } from "@/utils/dictionary";
import { WordPopup } from "@/components/WordPopup";
import { Modal } from "react-native";
import { toast } from "@/components/Toast";
import * as Haptics from "expo-haptics";
import * as Speech from "expo-speech";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { type ColorScheme } from "@/constants/colors";

// ─── Data Mapping ─────────────────────────────────────────────────────────────

const DATA_MAP: Record<string, { grammar: string; vocab: string }> = {
  "N1": { grammar: "", vocab: "n1_vocab.csv" },
  "N2": { grammar: "n2_grammar.json", vocab: "n2_vocab.csv" },
  "N3": { grammar: "n3_grammar.json", vocab: "n3_vocab.csv" },
  "N4": { grammar: "n4_grammar.json", vocab: "n4_vocab.csv" },
  "N5": { grammar: "n5_grammar.json", vocab: "n5_vocab.csv" },
};

const ITEMS_PER_LESSON = 50;

// ─── Types ────────────────────────────────────────────────────────────────────

interface GrammarItem {
  id: string;
  bunpou: string;
  arti_umum: string;
  penggunaan: string;
  pola: string;
  contoh: Array<{ kalimat_jepang: string; arti_indonesia: string }>;
  catatan?: string;
}

interface VocabItem {
  word: string;
  reading: string;
  id_mean: string;
  en_mean: string;
  vn_mean: string;
  kr_mean: string;
}

type ScreenMode = "hub" | "lesson" | "detail";

export default function JLPTLevelDetail() {
  const { level } = useLocalSearchParams<{ level: string }>();
  const colors = useColors();
  const { isDark, palette } = useTheme();
  const [searchQuery, setSearchQuery] = useState("");
  const [activeTab, setActiveTab] = useState<"grammar" | "vocab">("grammar");
  const tabAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.spring(tabAnim, {
      toValue: activeTab === "grammar" ? 0 : 1,
      useNativeDriver: true,
      tension: 50,
      friction: 8
    }).start();
  }, [activeTab]);
  const switchTab = (tab: "grammar" | "vocab") => {
    if (tab !== activeTab) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      setActiveTab(tab);
    }
  };

  const [isPrinting, setIsPrinting] = useState(false);

  const handlePrint = async () => {
    if (currentFullList.length === 0) return;
    setIsPrinting(true);
    try {
      const html = `
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #1f2937; }
              h1 { color: #4f46e5; text-align: center; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
              .level { text-align: center; font-size: 14px; color: #6b7280; margin-top: -10px; margin-bottom: 30px; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th { background-color: #f9fafb; color: #4b5563; text-align: left; padding: 12px; border: 1px solid #e5e7eb; font-size: 12px; text-transform: uppercase; }
              td { padding: 12px; border: 1px solid #e5e7eb; font-size: 14px; line-height: 1.5; }
              .jp { font-size: 18px; font-weight: bold; color: #111827; }
              tr:nth-child(even) { background-color: #f3f4f6; }
            </style>
          </head>
          <body>
            <h1>Materi JLPT ${level} - ${activeTab === 'grammar' ? 'Grammar' : 'Vocabulary'}</h1>
            <p class="level">Generated by Antigravity Learnpath</p>
            <table>
              <thead>
                <tr>
                  <th style="width: 50px">No</th>
                  <th>${activeTab === 'grammar' ? 'Materi' : 'Kata / Kanji'}</th>
                  <th>${activeTab === 'grammar' ? 'Arti & Penggunaan' : 'Bacaan & Arti'}</th>
                </tr>
              </thead>
              <tbody>
                ${currentFullList.map((item, idx) => `
                  <tr>
                    <td>${idx + 1}</td>
                    <td>
                      <div class="jp">${activeTab === 'grammar' ? (item as GrammarItem).bunpou : (item as VocabItem).word}</div>
                      ${activeTab === 'grammar' ? `<div style="font-size: 11px; color: #666; margin-top: 4px;">${(item as GrammarItem).pola}</div>` : ''}
                    </td>
                    <td>
                      <div>${activeTab === 'grammar' ? (item as GrammarItem).arti_umum : (item as VocabItem).id_mean}</div>
                      ${activeTab === 'vocab' ? `<div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Read: ${(item as VocabItem).reading}</div>` : ''}
                    </td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (e) {
      console.error(e);
      toast.error("Gagal membuat PDF.");
    } finally {
      setIsPrinting(false);
    }
  };

  const [courseDict, setCourseDict] = useState<DictEntry[]>([]);
  const [activeWord, setActiveWord] = useState<DictEntry | null>(null);
  const [showPopup, setShowPopup] = useState(false);

  const styles = useMemo(() => makeStyles(colors, isDark, palette), [colors, isDark, palette]);
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { width } = useWindowDimensions();

  // Navigation State
  const [mode, setMode] = useState<ScreenMode>("hub");
  // Data State
  const [loading, setLoading] = useState(true);
  const [grammarData, setGrammarData] = useState<GrammarItem[]>([]);
  const [vocabData, setVocabData] = useState<VocabItem[]>([]);
  
  // Lesson State
  const [selectedLessonIdx, setSelectedLessonIdx] = useState(0);
  const [fcIndex, setFcIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [isShuffled, setIsShuffled] = useState(false);
  const [grammarMode, setGrammarMode] = useState<"list" | "flashcard">("list");
  
  // Detail State
  const [selectedItem, setSelectedItem] = useState<GrammarItem | VocabItem | null>(null);

  // Mastery State
  const [mastery, setMastery] = useState<Record<string, { status: "mastered" | "failed" | "new" }>>({});
  const [filterMode, setFilterMode] = useState<"all" | "unmastered">("all");

  const getItemId = (item: GrammarItem | VocabItem) => {
    return "bunpou" in item ? `g_${item.bunpou}` : `v_${item.word}`;
  };

  const loadMastery = async () => {
    try {
      const key = `jlpt_mastery_${level}`;
      const data = await AsyncStorage.getItem(key);
      if (data) setMastery(JSON.parse(data));
    } catch (e) {
      console.error("Failed to load mastery:", e);
    }
  };

  const updateItemMastery = async (item: GrammarItem | VocabItem, status: "mastered" | "failed") => {
    if (!item) return;
    
    // Premium Haptic Feedback
    if (status === "mastered") {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      toast.success("Materi ditandai: Sudah Hapal! 🏆");
    } else {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      toast.info("Materi ditandai: Belum Hapal 📖");
    }

    const id = getItemId(item);
    const newMastery = { ...mastery, [id]: { status } };
    setMastery(newMastery);
    try {
      const key = `jlpt_mastery_${level}`;
      await AsyncStorage.setItem(key, JSON.stringify(newMastery));
    } catch (e) {
      console.error("Failed to save mastery:", e);
    }
  };

  const playSpeech = (text: string) => {
    // Strip brackets before speaking
    const clean = text.replace(/[\[\(「].*?[\]\)」]/g, "").trim();
    Speech.speak(clean, { language: "ja-JP", rate: 0.9 });
  };

  const renderHighlightedText = (text: string, baseStyle: any, highlightColor?: string) => {
    // Regex matches text inside 「」, [], or ()
    const parts = text.split(/([\[\(「].*?[\]\)」])/g);
    return (
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center' }}>
        {parts.map((part, i) => {
          const isBracketed = part.match(/^[\[\(「].*?[\]\)」]$/);
          if (isBracketed) {
            return (
              <Text key={i} style={[baseStyle, { color: highlightColor || colors.primary, opacity: 0.65, fontSize: (baseStyle.fontSize || 14) * 0.75, fontWeight: "600" }]}>
                {part}
              </Text>
            );
          }
          return <Text key={i} style={baseStyle}>{part}</Text>;
        })}
      </View>
    );
  };

  // Add to Course State
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [targetPaths, setTargetPaths] = useState<any[]>([]);
  const [selectedPathId, setSelectedPathId] = useState("");
  const [targetModules, setTargetModules] = useState<any[]>([]);
  const [selectedModId, setSelectedModId] = useState("");
  const [targetLessons, setTargetLessons] = useState<any[]>([]);
  const [selectedLessonId, setSelectedLessonId] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const openSaveModal = async (item: GrammarItem | VocabItem) => {
    setSelectedItem(item);
    const paths = await getLearningPaths();
    setTargetPaths(paths);
    setShowSaveModal(true);
  };

  useEffect(() => {
    if (selectedPathId) {
      getModules(selectedPathId).then(setTargetModules);
      setSelectedModId("");
      setTargetLessons([]);
      setSelectedLessonId("");
    }
  }, [selectedPathId]);

  useEffect(() => {
    if (selectedModId) {
      getLessons(selectedModId).then(setTargetLessons);
      setSelectedLessonId("");
    }
  }, [selectedModId]);

  const handleSaveToNote = async () => {
    if (!selectedLessonId || !selectedItem) {
      toast.error("Pilih pelajaran tujuan!");
      return;
    }
    setIsSaving(true);
    try {
      const isGrammar = "bunpou" in selectedItem;
      const title = `[JLPT ${level}] ${isGrammar ? (selectedItem as GrammarItem).bunpou : (selectedItem as VocabItem).word}`;
      
      let content = "";
      if (isGrammar) {
        const g = selectedItem as GrammarItem;
        content = `Arti: ${g.arti_umum}\n\nPenggunaan: ${g.penggunaan}\n\nPola: ${g.pola}\n\nContoh:\n${g.contoh.map(c => `- ${c.kalimat_jepang}\n  (${c.arti_indonesia})`).join("\n")}`;
      } else {
        const v = selectedItem as VocabItem;
        content = `Bacaan: ${v.reading}\n\nArti (ID): ${v.id_mean}\nArti (EN): ${v.en_mean}\nArti (VN): ${v.vn_mean}`;
      }

      await saveNote({
        id: generateId(),
        lessonId: selectedLessonId,
        title,
        content,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });

      toast.success("Berhasil ditambahkan ke kursus!");
      setShowSaveModal(false);
    } catch (e) {
      toast.error("Gagal menyimpan catatan.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleNext = () => {
    const items = getLessonItems(selectedLessonIdx);
    const currentIndex = items.findIndex(i => getItemId(i) === getItemId(selectedItem!));
    if (currentIndex < items.length - 1) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      setSelectedItem(items[currentIndex + 1]);
    }
  };

  const handlePrev = () => {
    const items = getLessonItems(selectedLessonIdx);
    const currentIndex = items.findIndex(i => getItemId(i) === getItemId(selectedItem!));
    if (currentIndex > 0) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      setSelectedItem(items[currentIndex - 1]);
    }
  };

  // ─── Back Action Handler ───────────────────────────────────────────────────

  useEffect(() => {
    const onBackPress = () => {
      if (mode === "detail") {
        setMode("lesson");
        return true;
      }
      if (mode === "lesson") {
        setMode("hub");
        return true;
      }
      return false;
    };
    const subscription = BackHandler.addEventListener("hardwareBackPress", onBackPress);
    return () => subscription.remove();
  }, [mode]);

  // ─── Data Loading ──────────────────────────────────────────────────────────

  const loadData = async () => {
    setLoading(true);
    try {
      const paths = DATA_MAP[level as string];
      if (!paths) return;

      const getUrl = (filename: string) => {
        if (Platform.OS === "web") {
          return `${window.location.origin}/jlpt-data/${filename}`;
        }
        const host = Constants.expoConfig?.hostUri?.split(':').shift() || 'localhost';
        return `http://${host}:8081/jlpt-data/${filename}`;
      };

      if (paths.grammar) {
        const url = getUrl(paths.grammar);
        const response = await fetch(url);
        const json = await response.json();
        let flattened: GrammarItem[] = [];
        if (json && json.data && Array.isArray(json.data)) {
          flattened = json.data.every(Array.isArray) ? json.data.flat(1) : json.data;
        }
        setGrammarData(flattened);
      }

      if (paths.vocab) {
        const url = getUrl(paths.vocab);
        const response = await fetch(url);
        const text = await response.text();
        
        const parseCSVLine = (line: string) => {
          const result = [];
          let current = "";
          let inQuotes = false;
          for (let i = 0; i < line.length; i++) {
            const char = line[i];
            if (char === '"') inQuotes = !inQuotes;
            else if (char === ',' && !inQuotes) {
              result.push(current);
              current = "";
            } else {
              current += char;
            }
          }
          result.push(current);
          return result;
        };

        const lines = text.split(/\r?\n/).filter(l => l.trim() !== "");
        const rawParsed: VocabItem[] = lines.slice(1).map(line => {
          const parts = parseCSVLine(line);
          return {
            word: (parts[0] || "").trim(),
            reading: (parts[1] || "").trim(),
            id_mean: (parts[2] || "").trim(),
            en_mean: (parts[3] || "").trim(),
            vn_mean: (parts[4] || "").trim(),
            kr_mean: (parts[5] || "").trim()
          };
        });

        // Deduplicate: Keep one entry per word, preferring the one with Kanji in brackets
        const seen = new Map<string, VocabItem>();
        rawParsed.forEach(item => {
           const base = item.word.replace(/[\[\(「].*$/g, "").trim();
           const existing = seen.get(base);
           if (!existing) {
             seen.set(base, item);
           } else {
             const hasKanji = (s: string) => s.includes("「") || s.includes("[") || s.includes("(");
             if (hasKanji(item.word) && !hasKanji(existing.word)) {
                seen.set(base, item);
             }
           }
        });
        const parsed = Array.from(seen.values());
        setVocabData(parsed);
      }
    } catch (error) {
      console.error("[JLPT] Load failed:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
    loadMastery();
    getCourseDictionary().then(setCourseDict);
    if (level === "N1") setActiveTab("vocab");
  }, [level]);

  // ─── Helpers ───────────────────────────────────────────────────────────────

  const currentFullList = activeTab === "grammar" ? grammarData : vocabData;
  const lessonsCount = Math.ceil(currentFullList.length / ITEMS_PER_LESSON);

  const getLessonItems = (idx: number) => {
    const start = idx * ITEMS_PER_LESSON;
    const baseItems = currentFullList.slice(start, start + ITEMS_PER_LESSON);
    if (isShuffled) {
      // Fisher-Yates Shuffle deterministic for the current state
      const shuffled = [...baseItems];
      for (let i = shuffled.length - 1; i > 0; i--) {
        const j = (i * 31 + idx) % (i + 1); // Simple pseudo-random based on index
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
      }
      return shuffled;
    }
    return baseItems;
  };

  const filteredHubData = useMemo(() => {
    if (!searchQuery) return [];
    const q = searchQuery.toLowerCase();
    return currentFullList.filter(i => {
      if (activeTab === "grammar") {
        const g = i as GrammarItem;
        return (g.bunpou || "").toLowerCase().includes(q) || (g.arti_umum || "").toLowerCase().includes(q);
      } else {
        const v = i as VocabItem;
        return (v.word || "").toLowerCase().includes(q) || (v.reading || "").toLowerCase().includes(q) || (v.id_mean || "").toLowerCase().includes(q);
      }
    });
  }, [currentFullList, searchQuery, activeTab]);

  // ─── Renderers ─────────────────────────────────────────────────────────────

  const renderHub = () => (
    <View style={styles.hubContainer}>
      <LinearGradient colors={[colors.primary, colors.purple]} style={[styles.headerHub, { paddingTop: insets.top + 10 }]}>
        <View style={styles.topBar}>
          <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
            <ArrowLeft size={20} color="#fff" />
          </TouchableOpacity>
          <Text style={styles.hubTitle}>JLPT {level}</Text>
          <TouchableOpacity 
            onPress={handlePrint} 
            style={[styles.iconBtn, isPrinting && { opacity: 0.5 }]} 
            disabled={isPrinting}
          >
            {isPrinting ? (
              <ActivityIndicator size="small" color="#fff" />
            ) : (
              <Feather name="printer" size={18} color="#fff" />
            )}
          </TouchableOpacity>
        </View>

        <View style={styles.tabBar}>
          <Animated.View 
            style={[
              styles.tabSlider, 
              { 
                width: level === "N1" ? "100%" : "50%",
                transform: [{ 
                  translateX: tabAnim.interpolate({ 
                    inputRange: [0, 1], 
                    outputRange: [0, (width - 52) / 2] 
                  }) 
                }] 
              }
            ]} 
          >
            <LinearGradient 
              colors={["#FFFFFF", "#F3F4F6"]}
              style={{ flex: 1, borderRadius: 25 }}
            />
          </Animated.View>
          {level !== "N1" && (
            <TouchableOpacity 
              style={styles.tab}
              onPress={() => switchTab("grammar")}
            >
              <BookOpen size={20} color={activeTab === "grammar" ? colors.primary : "rgba(255,255,255,0.5)"} />
              <Text style={[styles.tabText, activeTab === "grammar" && styles.activeTabText]}>Grammar</Text>
            </TouchableOpacity>
          )}
          <TouchableOpacity 
            style={[styles.tab, level === "N1" && { flex: 1 }]}
            onPress={() => switchTab("vocab")}
          >
            <Book size={20} color={activeTab === "vocab" ? colors.primary : "rgba(255,255,255,0.5)"} />
            <Text style={[styles.tabText, activeTab === "vocab" && styles.activeTabText]}>Vocab</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.searchRow}>
          <View style={styles.searchBox}>
            <Search size={18} color="rgba(255,255,255,0.6)" />
            <TextInput
              style={styles.searchInput}
              placeholder={`Cari materi ${activeTab}...`}
              placeholderTextColor="rgba(255,255,255,0.4)"
              value={searchQuery}
              onChangeText={setSearchQuery}
            />
          </View>
          <TouchableOpacity 
            style={[styles.filterBtn, filterMode === "unmastered" && styles.filterBtnActive]}
            onPress={() => {
              Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
              setFilterMode(filterMode === "all" ? "unmastered" : "all");
            }}
          >
            <Feather name="layers" size={18} color="#fff" />
            {filterMode === "unmastered" && <View style={styles.filterDot} />}
          </TouchableOpacity>
        </View>
      </LinearGradient>

      <ScrollView contentContainerStyle={styles.hubContent}>
        {level === "N5" && !searchQuery && (
          <View style={styles.n5Hero}>
            <LinearGradient colors={["rgba(255,255,255,0.1)", "transparent"]} style={styles.n5HeroGrad}>
              <View style={styles.n5HeroRow}>
                <View style={styles.n5HeroIcon}>
                  <Award size={32} color={colors.amber} />
                </View>
                <View style={styles.n5HeroText}>
                  <Text style={styles.n5HeroTitle}>Starter Mastery (N5)</Text>
                  <Text style={styles.n5HeroSub}>Landasan utama Bahasa Jepang kamu dimulai dari sini.</Text>
                </View>
              </View>
              <View style={styles.n5HeroStats}>
                <View style={styles.n5StatItem}>
                  <Text style={styles.n5StatVal}>{grammarData.length + vocabData.length}</Text>
                  <Text style={styles.n5StatLabel}>Total Materi</Text>
                </View>
                <View style={styles.n5StatDivider} />
                <View style={styles.n5StatItem}>
                  <Text style={styles.n5StatVal}>~30 Hari</Text>
                  <Text style={styles.n5StatLabel}>Estimasi</Text>
                </View>
                <TouchableOpacity style={styles.n5ResumeBtn} onPress={() => { setSelectedLessonIdx(0); setMode("lesson"); }}>
                  <Play size={14} color="#fff" />
                  <Text style={styles.n5ResumeText}>Mulai</Text>
                </TouchableOpacity>
              </View>
            </LinearGradient>
          </View>
        )}

        {loading ? (
          <ActivityIndicator color={colors.primary} style={{ marginTop: 40 }} />
        ) : searchQuery ? (
          filteredHubData.map((item, idx) => (
            <TouchableOpacity key={idx} style={styles.searchResult} onPress={() => { setSelectedItem(item); setMode("detail"); }}>
              <View style={{ flex: 1 }}>
                {"bunpou" in item ? (
                  <Text style={styles.searchResultText}>{item.bunpou}</Text>
                ) : (
                  renderHighlightedText(item.word, styles.searchResultText)
                )}
              </View>
              <ChevronRight size={16} color={colors.textMuted} />
            </TouchableOpacity>
          ))
        ) : (
          <View style={styles.lessonGrid}>
            {Array.from({ length: lessonsCount }).map((_, idx) => {
              const lessonItems = getLessonItems(idx);
              const filteredItems = filterMode === "unmastered" 
                ? lessonItems.filter(item => mastery[getItemId(item)]?.status !== "mastered")
                : lessonItems;
                
              if (filteredItems.length === 0 && filterMode === "unmastered") return null;

              const firstItem = filteredItems[0] || lessonItems[0];
              const previewText = firstItem ? ("bunpou" in firstItem ? firstItem.bunpou : firstItem.word) : "...";
              
              // Calculate progress
              const masteredCount = lessonItems.filter(item => mastery[getItemId(item)]?.status === "mastered").length;
              const progress = (masteredCount / lessonItems.length) * 100;

              return (
                <TouchableOpacity 
                  key={idx} 
                  style={styles.lessonCard}
                  onPress={() => {
                    setSelectedLessonIdx(idx);
                    setFcIndex(0);
                    setIsFlipped(false);
                    setMode("lesson");
                  }}
                >
                  <View style={styles.lessonTop}>
                    <View style={styles.lessonInfoWrap}>
                      <Text style={styles.lessonTitle}>Materi {idx + 1}</Text>
                      <Text style={styles.lessonPreview}>{previewText}...</Text>
                    </View>
                    <View style={[styles.lessonBadge, progress === 100 && styles.lessonBadgeMastered]}>
                      {progress === 100 ? (
                        <Trophy size={14} color="#059669" />
                      ) : (
                        <Text style={styles.lessonBadgeText}>{filterMode === "unmastered" ? `${filteredItems.length} SISA` : "AKTIF"}</Text>
                      )}
                    </View>
                  </View>

                  <View style={styles.lessonBottom}>
                    <View style={styles.lessonStatsRow}>
                      <Text style={styles.lessonStatText}>{masteredCount}/{lessonItems.length} Sudah Hapal</Text>
                      <Text style={styles.lessonStatPct}>{Math.round(progress)}%</Text>
                    </View>
                    <View style={styles.lessonBarTrack}>
                      <LinearGradient 
                        colors={progress === 100 ? ["#10B981", "#059669"] : ["#4F46E5", "#7C3AED"]}
                        start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
                        style={[styles.lessonBarFill, { width: `${Math.max(5, progress)}%` }]} 
                      />
                    </View>
                  </View>
                </TouchableOpacity>
              );
            })}
          </View>
        )}
      </ScrollView>
    </View>
  );

  const renderGrammarStudy = () => {
    const items = getLessonItems(selectedLessonIdx);
    
    if (grammarMode === "flashcard") {
      const item = items[fcIndex] as GrammarItem;
      if (!item) return null;

      return (
        <View style={styles.fullScreen}>
          <LinearGradient colors={[colors.primary, colors.purple]} style={[styles.miniHeader, { paddingTop: insets.top + 10 }]}>
            <TouchableOpacity onPress={() => setMode("hub")} style={styles.iconBtn}>
              <ArrowLeft size={20} color="#fff" />
            </TouchableOpacity>
            <View style={{ alignItems: 'center' }}>
              <Text style={styles.miniHeaderTitle}>Grammar Flashcard</Text>
              <View style={styles.premiumProgress}>
                <View style={[styles.premiumProgressBar, { width: `${((fcIndex + 1) / items.length) * 100}%` }]} />
              </View>
            </View>
            <TouchableOpacity onPress={() => setGrammarMode("list")} style={styles.iconBtn}>
              <Feather name="list" size={18} color="#fff" />
            </TouchableOpacity>
          </LinearGradient>

          <View style={styles.premiumGameContainer}>
            <TouchableOpacity 
              activeOpacity={0.95} 
              onPress={() => setIsFlipped(!isFlipped)} 
              style={[styles.premiumCard, isFlipped ? styles.cardBackPremium : styles.cardFrontPremium]}
            >
              <View style={styles.premiumCardInner}>
                <View style={styles.cardTag}>
                  <BookOpen size={10} color={colors.primary} />
                  <Text style={styles.cardTagText}>{isFlipped ? "ARTI & POLA" : "BUNPOU"}</Text>
                </View>

                {!isFlipped ? (
                  <>
                    <Text style={[styles.premiumCardMain, { fontSize: 32 }]}>{item.bunpou}</Text>
                    <View style={styles.polaBoxMini}>
                      <Text style={styles.polaTextMini}>{item.pola}</Text>
                    </View>
                  </>
                ) : (
                  <ScrollView contentContainerStyle={{ alignItems: 'center', paddingVertical: 40 }}>
                    <Text style={styles.premiumCardMeaning}>{item.arti_umum}</Text>
                    <View style={styles.grammarFlashDetail}>
                      <Text style={styles.grammarFlashLabel}>CONTOH:</Text>
                      {item.contoh?.slice(0, 2).map((ex, i) => (
                        <View key={i} style={styles.grammarFlashEx}>
                          <Text style={styles.grammarFlashExJp}>{ex.kalimat_jepang}</Text>
                          <Text style={styles.grammarFlashExId}>{ex.arti_indonesia}</Text>
                        </View>
                      ))}
                    </View>
                  </ScrollView>
                )}

                <View style={styles.premiumTapHint}>
                  <RotateCcw size={14} color={colors.textMuted} />
                  <Text style={styles.premiumTapHintText}>TAP TO FLIP</Text>
                </View>
              </View>
            </TouchableOpacity>

            <View style={styles.premiumNav}>
              {isFlipped ? (
                <View style={styles.tracingContainer}>
                  <TouchableOpacity 
                    style={[styles.tracingBtn, styles.wrongBtn]}
                    onPress={() => {
                      updateItemMastery(item, "failed");
                      if (fcIndex < items.length - 1) {
                        setFcIndex(fcIndex + 1);
                        setIsFlipped(false);
                      } else {
                        setMode("hub");
                      }
                    }}
                  >
                    <AlertCircle size={20} color="#fff" />
                    <Text style={styles.tracingBtnText}>BELUM HAPAL</Text>
                  </TouchableOpacity>

                  <TouchableOpacity 
                    style={[styles.tracingBtn, styles.correctBtn]}
                    onPress={() => {
                      updateItemMastery(item, "mastered");
                      if (fcIndex < items.length - 1) {
                        setFcIndex(fcIndex + 1);
                        setIsFlipped(false);
                      } else {
                        setMode("hub");
                      }
                    }}
                  >
                    <CheckCircle2 size={20} color="#fff" />
                    <Text style={styles.tracingBtnText}>SUDAH HAPAL</Text>
                  </TouchableOpacity>
                </View>
              ) : (
                <>
                  <TouchableOpacity 
                    style={[styles.premiumNavBtn, fcIndex === 0 && styles.disabledBtn]} 
                    disabled={fcIndex === 0}
                    onPress={() => { setFcIndex(fcIndex - 1); setIsFlipped(false); }}
                  >
                    <ArrowLeft size={24} color={colors.text} />
                  </TouchableOpacity>

                  <TouchableOpacity 
                    style={styles.premiumNextBtn}
                    onPress={() => setIsFlipped(true)}
                  >
                    <Text style={styles.premiumNextBtnText}>LIHAT DETAIL</Text>
                    <ChevronRight size={20} color="#fff" />
                  </TouchableOpacity>
                </>
              )}
            </View>
          </View>
        </View>
      );
    }

    return (
      <View style={styles.fullScreen}>
        <LinearGradient colors={[colors.primary, colors.purple]} style={[styles.miniHeader, { paddingTop: insets.top + 10 }]}>
          <TouchableOpacity onPress={() => setMode("hub")} style={styles.iconBtn}>
            <ArrowLeft size={20} color="#fff" />
          </TouchableOpacity>
          <View style={{ alignItems: 'center' }}>
            <Text style={styles.miniHeaderTitle}>Lesson {selectedLessonIdx + 1}</Text>
            <TouchableOpacity style={styles.shuffleToggle} onPress={() => {
               Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
               setIsShuffled(!isShuffled);
            }}>
              <Feather name="shuffle" size={12} color={isShuffled ? colors.amber : "#fff"} />
              <Text style={[styles.shuffleToggleText, isShuffled && { color: colors.amber }]}>
                {isShuffled ? "SHUFFLE ON" : "SHUFFLE OFF"}
              </Text>
            </TouchableOpacity>
          </View>
          <TouchableOpacity onPress={() => setGrammarMode("flashcard")} style={styles.iconBtn}>
            <Sparkles size={18} color="#fff" />
          </TouchableOpacity>
        </LinearGradient>

        <FlatList
          data={items as any[]}
          keyExtractor={(item, index) => index.toString()}
          contentContainerStyle={styles.studyList}
          renderItem={({ item, index }) => {
            const isMastered = mastery[getItemId(item)]?.status === "mastered";
            const isFailed = mastery[getItemId(item)]?.status === "failed";
            
            return (
              <View style={[styles.studyItem, isMastered && styles.studyItemMastered]}>
                <TouchableOpacity 
                  style={styles.studyItemMain}
                  onPress={() => { setSelectedItem(item); setMode("detail"); }}
                >
                  <View style={[styles.studyItemBadge, isMastered && { backgroundColor: "#D1FAE5" }]}>
                    {isMastered ? (
                      <Check size={14} color="#059669" />
                    ) : (
                      <Text style={styles.studyItemIndex}>{index + 1}</Text>
                    )}
                  </View>
                  <View style={styles.studyItemContent}>
                    <Text style={[styles.studyItemTitle, isMastered && { color: "#059669" }]}>{(item as GrammarItem).bunpou}</Text>
                    <Text style={styles.studyItemSub} numberOfLines={1}>{(item as GrammarItem).arti_umum}</Text>
                  </View>
                </TouchableOpacity>

                <View style={styles.studyItemActions}>
                  <TouchableOpacity 
                    onPress={() => updateItemMastery(item, "failed")}
                    style={[styles.smallMasteryBtn, isFailed && { backgroundColor: colors.danger, borderColor: colors.danger }]}
                    hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
                  >
                    <X size={14} color={isFailed ? "#fff" : colors.textMuted} />
                  </TouchableOpacity>
                  <TouchableOpacity 
                    onPress={() => updateItemMastery(item, "mastered")}
                    style={[styles.smallMasteryBtn, isMastered && { backgroundColor: colors.success, borderColor: colors.success }]}
                    hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
                  >
                    <Check size={14} color={isMastered ? "#fff" : colors.textMuted} />
                  </TouchableOpacity>
                </View>
              </View>
            );
          }}
        />
      </View>
    );
  };

  const renderVocabFlashcards = () => {
    const items = getLessonItems(selectedLessonIdx);
    const item = items[fcIndex];
    if (!item) return null;

    return (
      <View style={styles.fullScreen}>
        <LinearGradient colors={[colors.primary, colors.purple]} style={[styles.miniHeader, { paddingTop: insets.top + 10 }]}>
          <TouchableOpacity onPress={() => setMode("hub")} style={styles.iconBtn}>
            <ArrowLeft size={20} color="#fff" />
          </TouchableOpacity>
          <View style={{ alignItems: 'center' }}>
            <Text style={styles.miniHeaderTitle}>Lesson {selectedLessonIdx + 1}</Text>
            <TouchableOpacity style={styles.shuffleToggle} onPress={() => {
               Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
               setIsShuffled(!isShuffled);
            }}>
              <Feather name="shuffle" size={12} color={isShuffled ? colors.amber : "#fff"} />
              <Text style={[styles.shuffleToggleText, isShuffled && { color: colors.amber }]}>
                {isShuffled ? "SHUFFLE ON" : "SHUFFLE OFF"}
              </Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.miniHeaderCount}>{fcIndex + 1}/{items.length}</Text>
        </LinearGradient>

        <View style={styles.premiumGameContainer}>
          <TouchableOpacity 
            activeOpacity={0.95} 
            onPress={() => setIsFlipped(!isFlipped)} 
            style={[styles.premiumCard, isFlipped ? styles.cardBackPremium : styles.cardFrontPremium]}
          >
            <View style={styles.premiumCardInner}>
              <View style={styles.cardTag}>
                <Sparkles size={10} color={colors.primary} />
                <Text style={styles.cardTagText}>{isFlipped ? "MEANING" : "VOCABULARY"}</Text>
              </View>

              {!isFlipped ? (
                <>
                  <View style={styles.tokenRow}>
                    {renderHighlightedText((item as VocabItem).word, styles.premiumCardMain)}
                  </View>
                  <TouchableOpacity onPress={() => playSpeech((item as VocabItem).word)} style={styles.speechBtn}>
                    <Volume2 size={24} color={colors.primary} />
                  </TouchableOpacity>
                  <Text style={styles.premiumCardSub}>{(item as VocabItem).reading}</Text>
                </>
              ) : (
                <>
                  <Text style={styles.premiumCardMeaning}>{(item as VocabItem).id_mean}</Text>
                  <TouchableOpacity onPress={() => playSpeech((item as VocabItem).word)} style={styles.speechBtn}>
                    <Volume2 size={24} color={colors.primary} />
                  </TouchableOpacity>
                  <View style={styles.premiumCardSecondary}>
                    <Text style={styles.premiumCardSecondaryText}>EN: {(item as VocabItem).en_mean}</Text>
                  </View>
                </>
              )}

              <View style={styles.premiumTapHint}>
                <RotateCcw size={14} color={colors.textMuted} />
                <Text style={styles.premiumTapHintText}>TAP TO FLIP</Text>
              </View>
            </View>
          </TouchableOpacity>

          <View style={styles.premiumNav}>
            {isFlipped ? (
              <View style={styles.tracingContainer}>
                <TouchableOpacity 
                  style={[styles.tracingBtn, styles.wrongBtn]}
                  onPress={() => {
                    updateItemMastery(item, "failed");
                    if (fcIndex < items.length - 1) {
                      setFcIndex(fcIndex + 1);
                      setIsFlipped(false);
                    } else {
                      setMode("hub");
                    }
                  }}
                >
                  <AlertCircle size={20} color="#fff" />
                  <Text style={styles.tracingBtnText}>BELUM HAPAL</Text>
                </TouchableOpacity>

                <TouchableOpacity 
                  style={[styles.tracingBtn, styles.correctBtn]}
                  onPress={() => {
                    updateItemMastery(item, "mastered");
                    if (fcIndex < items.length - 1) {
                      setFcIndex(fcIndex + 1);
                      setIsFlipped(false);
                    } else {
                      setMode("hub");
                    }
                  }}
                >
                  <CheckCircle2 size={20} color="#fff" />
                  <Text style={styles.tracingBtnText}>SUDAH HAPAL</Text>
                </TouchableOpacity>
              </View>
            ) : (
              <>
                <TouchableOpacity 
                  style={[styles.premiumNavBtn, fcIndex === 0 && styles.disabledBtn]} 
                  disabled={fcIndex === 0}
                  onPress={() => { setFcIndex(fcIndex - 1); setIsFlipped(false); }}
                >
                  <ArrowLeft size={24} color={colors.text} />
                </TouchableOpacity>

                <TouchableOpacity 
                  style={styles.premiumNextBtn}
                  onPress={() => setIsFlipped(true)}
                >
                  <Text style={styles.premiumNextBtnText}>LIHAT ARTI</Text>
                  <ChevronRight size={20} color="#fff" />
                </TouchableOpacity>
              </>
            )}
          </View>
        </View>
      </View>
    );
  };

  const renderLessonFlashcard = () => {
    return activeTab === "grammar" ? renderGrammarStudy() : renderVocabFlashcards();
  };

  const renderDetail = () => {
    if (!selectedItem) return null;
    const isGrammar = "bunpou" in selectedItem;

    return (
      <View style={styles.fullScreen}>
        <View style={[styles.detailHeader, { paddingTop: insets.top + 10 }]}>
          <TouchableOpacity onPress={() => setMode("lesson")} style={styles.detailBackBtn}>
            <X size={24} color={colors.text} />
          </TouchableOpacity>
          <Text style={styles.detailHeaderTitle}>Detail Materi</Text>
          <View style={{ width: 44 }} />
        </View>

        <ScrollView contentContainerStyle={styles.detailContent}>
          <View style={styles.detailHero}>
            {isGrammar ? (
              <Text style={styles.heroMain}>{(selectedItem as GrammarItem).bunpou}</Text>
            ) : (
              renderHighlightedText((selectedItem as VocabItem).word, styles.heroMain)
            )}
            <Text style={styles.heroSub}>{isGrammar ? (selectedItem as GrammarItem).arti_umum : (selectedItem as VocabItem).reading}</Text>
          </View>

          {isGrammar ? (
            <>
              <View style={styles.detailSection}>
                <View style={styles.sectionHead}><Info size={16} color={colors.primary} /><Text style={styles.sectionLabel}>PENGGUNAAN</Text></View>
                <Text style={styles.sectionText}>{(selectedItem as GrammarItem).penggunaan}</Text>
              </View>
              <View style={styles.detailSection}>
                <View style={styles.sectionHead}><Hash size={16} color={colors.primary} /><Text style={styles.sectionLabel}>POLA KALIMAT</Text></View>
                <View style={styles.polaBox}><Text style={styles.polaText}>{(selectedItem as GrammarItem).pola}</Text></View>
              </View>
              <View style={styles.detailSection}>
                <View style={styles.sectionHead}><BookOpen size={16} color={colors.primary} /><Text style={styles.sectionLabel}>CONTOH KALIMAT</Text></View>
                {(selectedItem as GrammarItem).contoh?.map((ex, i) => (
                  <View key={i} style={styles.exampleCard}>
                    <Text style={styles.exJp}>{ex.kalimat_jepang}</Text>
                    <Text style={styles.exId}>{ex.arti_indonesia}</Text>
                  </View>
                ))}
                </View>
            </>
          ) : (
            <>
              <View style={styles.meanGrid}>
                {[
                  { lang: 'INDONESIA', val: (selectedItem as VocabItem).id_mean },
                  { lang: 'ENGLISH', val: (selectedItem as VocabItem).en_mean },
                  { lang: 'VIETNAMESE', val: (selectedItem as VocabItem).vn_mean }
                ].map((m, i) => (
                  <View key={i} style={styles.meanRow}>
                    <Text style={styles.meanLabel}>{m.lang}</Text>
                    <Text style={styles.meanVal}>{m.val}</Text>
                  </View>
                ))}
              </View>
              <TouchableOpacity style={styles.speakBtn}>
                <Volume2 size={20} color="#fff" />
                <Text style={styles.speakBtnText}>Dengarkan Audio</Text>
              </TouchableOpacity>
            </>
          )}

          <View style={styles.detailMasteryRow}>
            <TouchableOpacity 
              style={[styles.detailMasteryBtn, styles.wrongBtn, mastery[getItemId(selectedItem)]?.status === "failed" && { backgroundColor: "#B91C1C", transform: [{scale: 0.98}] }]}
              onPress={() => updateItemMastery(selectedItem, "failed")}
            >
              <AlertCircle size={20} color="#fff" />
              <Text style={styles.detailMasteryBtnText}>BELUM HAPAL</Text>
            </TouchableOpacity>

            <TouchableOpacity 
              style={[styles.detailMasteryBtn, styles.correctBtn, mastery[getItemId(selectedItem)]?.status === "mastered" && { backgroundColor: "#047857", transform: [{scale: 0.98}] }]}
              onPress={() => updateItemMastery(selectedItem, "mastered")}
            >
              <CheckCircle2 size={20} color="#fff" />
              <Text style={styles.detailMasteryBtnText}>SUDAH HAPAL</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.detailNavRow}>
            <TouchableOpacity 
              style={[styles.detailNavBtn, selectedItem && getLessonItems(selectedLessonIdx).findIndex(i => getItemId(i) === getItemId(selectedItem)) === 0 && { opacity: 0.3 }]} 
              onPress={handlePrev}
              disabled={selectedItem && getLessonItems(selectedLessonIdx).findIndex(i => getItemId(i) === getItemId(selectedItem)) === 0}
            >
              <Feather name="chevron-left" size={20} color={colors.text} />
              <Text style={styles.detailNavBtnText}>PREV</Text>
            </TouchableOpacity>

            <View style={styles.detailNavCenter}>
              <Text style={styles.detailNavPos}>
                {getLessonItems(selectedLessonIdx).findIndex(i => getItemId(i) === getItemId(selectedItem!)) + 1} / {getLessonItems(selectedLessonIdx).length}
              </Text>
            </View>

            <TouchableOpacity 
              style={[styles.detailNavBtn, selectedItem && getLessonItems(selectedLessonIdx).findIndex(i => getItemId(i) === getItemId(selectedItem)) === getLessonItems(selectedLessonIdx).length - 1 && { opacity: 0.3 }]} 
              onPress={handleNext}
              disabled={selectedItem && getLessonItems(selectedLessonIdx).findIndex(i => getItemId(i) === getItemId(selectedItem)) === getLessonItems(selectedLessonIdx).length - 1}
            >
              <Text style={styles.detailNavBtnText}>NEXT</Text>
              <Feather name="chevron-right" size={20} color={colors.text} />
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.addToCourseBtn} onPress={() => openSaveModal(selectedItem)}>
            <FilePlus size={20} color={colors.primary} />
            <Text style={styles.addToCourseBtnText}>Tambahkan ke Kursus Saya</Text>
          </TouchableOpacity>
        </ScrollView>

        <Modal visible={showSaveModal} transparent animationType="slide">
          <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Simpan ke Kursus</Text>
                <TouchableOpacity onPress={() => setShowSaveModal(false)}>
                  <X size={24} color={colors.text} />
                </TouchableOpacity>
              </View>

              <Text style={styles.modalLabel}>Pilih Kursus</Text>
              <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.pathPicker}>
                {targetPaths.map(p => (
                  <TouchableOpacity 
                    key={p.id} 
                    style={[styles.pathChip, selectedPathId === p.id && styles.pathChipActive]}
                    onPress={() => setSelectedPathId(p.id)}
                  >
                    <Text style={[styles.pathChipText, selectedPathId === p.id && styles.pathChipTextActive]}>{p.name}</Text>
                  </TouchableOpacity>
                ))}
              </ScrollView>

              {selectedPathId && (
                <>
                  <Text style={styles.modalLabel}>Pilih Modul</Text>
                  <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.pathPicker}>
                    {targetModules.map(m => (
                      <TouchableOpacity 
                        key={m.id} 
                        style={[styles.pathChip, selectedModId === m.id && styles.pathChipActive]}
                        onPress={() => setSelectedModId(m.id)}
                      >
                        <Text style={[styles.pathChipText, selectedModId === m.id && styles.pathChipTextActive]}>{m.name}</Text>
                      </TouchableOpacity>
                    ))}
                  </ScrollView>
                </>
              )}

              {selectedModId && (
                <>
                  <Text style={styles.modalLabel}>Pilih Pelajaran (Lesson)</Text>
                  <ScrollView style={styles.lessonPicker}>
                    {targetLessons.map(l => (
                      <TouchableOpacity 
                        key={l.id} 
                        style={[styles.lessonPickItem, selectedLessonId === l.id && styles.lessonPickItemActive]}
                        onPress={() => setSelectedLessonId(l.id)}
                      >
                        <Text style={[styles.lessonPickText, selectedLessonId === l.id && styles.lessonPickTextActive]}>{l.name}</Text>
                        {selectedLessonId === l.id && <Check size={18} color={colors.primary} />}
                      </TouchableOpacity>
                    ))}
                  </ScrollView>
                </>
              )}

              <TouchableOpacity 
                style={[styles.saveConfirmBtn, (!selectedLessonId || isSaving) && styles.disabledBtn]}
                onPress={handleSaveToNote}
                disabled={!selectedLessonId || isSaving}
              >
                {isSaving ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveConfirmText}>SIMPAN SEBAGAI CATATAN</Text>}
              </TouchableOpacity>
            </View>
          </View>
        </Modal>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      {mode === "hub" && renderHub()}
      {mode === "lesson" && renderLessonFlashcard()}
      {mode === "detail" && renderDetail()}
      <WordPopup visible={showPopup} entry={activeWord} onClose={() => setShowPopup(false)} />
    </View>
  );
}

const makeStyles = (c: ColorScheme, isDark: boolean, palette: string) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.background },
  fullScreen: { flex: 1, backgroundColor: c.background },
  
  // Hub Styles
  hubContainer: { flex: 1 },
  headerHub: { paddingHorizontal: 20, paddingBottom: 30, borderBottomLeftRadius: 40, borderBottomRightRadius: 40 },
  topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 25 },
  hubTitle: { fontSize: 24, fontWeight: "900", color: "#fff" },
  iconBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },
  
  tabBar: { 
    flexDirection: "row", 
    backgroundColor: "rgba(0,0,0,0.22)", 
    borderRadius: 32, 
    padding: 6, 
    marginBottom: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    position: 'relative',
    overflow: 'hidden',
    height: 64
  },
  tabSlider: {
    position: 'absolute',
    top: 6,
    left: 6,
    bottom: 6,
    borderRadius: 26,
    elevation: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    zIndex: 0
  },
  tab: { 
    flex: 1, 
    flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "center", 
    gap: 12, 
    zIndex: 1
  },
  tabText: { fontSize: 13, fontWeight: "900", color: "rgba(255,255,255,0.5)", letterSpacing: 1, textTransform: "uppercase" },
  activeTabText: { color: c.primary },
  
  searchRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  searchBox: { flex: 1, flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.2)", borderRadius: 16, paddingHorizontal: 15, height: 52 },
  filterBtn: { width: 52, height: 52, borderRadius: 16, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },
  filterBtnActive: { backgroundColor: c.accent, borderWidth: 1, borderColor: "rgba(255,255,255,0.5)" },
  filterDot: { position: "absolute", top: 12, right: 12, width: 8, height: 8, borderRadius: 4, backgroundColor: "#fff", borderWidth: 1.5, borderColor: c.accent },
  searchInput: { flex: 1, color: "#fff", fontSize: 16, marginLeft: 12, fontWeight: "600" },

  hubContent: { padding: 20 },
  searchResult: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: c.surface, padding: 18, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: c.border },
  searchResultText: { fontSize: 16, fontWeight: "800", color: c.text },
  lessonGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 15 },
  lessonCard: { 
    width: '100%', 
    backgroundColor: c.surface, 
    borderRadius: 24, 
    padding: 20, 
    borderWidth: 1, 
    borderColor: c.border, 
    marginBottom: 16,
    elevation: 4, 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.08, 
    shadowRadius: 12 
  },
  lessonTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 },
  lessonInfoWrap: { flex: 1 },
  lessonTitle: { fontSize: 18, fontWeight: "900", color: c.text, letterSpacing: -0.5 },
  lessonPreview: { fontSize: 13, color: c.textMuted, fontWeight: "600", marginTop: 2 },
  lessonBadge: { backgroundColor: c.primaryLight, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10, minWidth: 50, alignItems: "center" },
  lessonBadgeMastered: { backgroundColor: "#D1FAE5" },
  lessonBadgeText: { fontSize: 9, fontWeight: "900", color: c.primary, letterSpacing: 0.5 },
  lessonBottom: { gap: 10 },
  lessonStatsRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  lessonStatText: { fontSize: 11, fontWeight: "800", color: c.textMuted },
  lessonStatPct: { fontSize: 12, fontWeight: "900", color: c.text },
  lessonBarTrack: { height: 10, backgroundColor: c.background, borderRadius: 5, overflow: "hidden" },
  lessonBarFill: { height: "100%", borderRadius: 5 },

  miniHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 20, borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
  miniHeaderTitle: { fontSize: 18, fontWeight: "900", color: "#fff" },
  miniHeaderCount: { fontSize: 14, fontWeight: "800", color: "rgba(255,255,255,0.8)" },


  // Grammar Study List Styles
  studyList: { padding: 20, gap: 12 },
  studyItem: { 
    flexDirection: "row", 
    alignItems: "center", 
    backgroundColor: c.surface, 
    padding: 16, 
    borderRadius: 20, 
    borderWidth: 1, 
    borderColor: c.border,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5
  },
  studyItemMastered: {
    borderColor: "#10B98133",
    backgroundColor: isDark ? "rgba(16, 185, 129, 0.05)" : "#F0FDF4"
  },
  studyItemBadge: { 
    width: 32, 
    height: 32, 
    borderRadius: 10, 
    backgroundColor: c.primaryLight, 
    alignItems: "center", 
    justifyContent: "center", 
    marginRight: 15 
  },
  studyItemIndex: { fontSize: 12, fontWeight: "900", color: c.primary },
  studyItemMain: { flex: 1, flexDirection: "row", alignItems: "center" },
  studyItemContent: { flex: 1 },
  studyItemTitle: { fontSize: 18, fontWeight: "800", color: c.text, marginBottom: 2 },
  studyItemSub: { fontSize: 13, color: c.textMuted, fontWeight: "600" },
  studyItemActions: { flexDirection: "row", gap: 8, paddingLeft: 10 },
  smallMasteryBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: c.background, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: c.border },

  // Detail Mastery
  detailMasteryRow: { flexDirection: "row", gap: 12, marginBottom: 20 },
  detailMasteryBtn: { flex: 1, height: 56, borderRadius: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, elevation: 4, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8 },
  detailMasteryBtnText: { color: "#fff", fontSize: 13, fontWeight: "900", letterSpacing: 1 },

  detailNavRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginVertical: 20 },
  detailNavBtn: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 10 },
  detailNavBtnText: { fontSize: 12, fontWeight: "800", color: c.textMuted },
  detailNavCenter: { backgroundColor: c.background, paddingHorizontal: 15, paddingVertical: 5, borderRadius: 12 },
  detailNavPos: { fontSize: 13, fontWeight: "900", color: c.primary },

  // Premium Flashcard Styles
  premiumGameContainer: { flex: 1, padding: 25, justifyContent: "center" },
  premiumCard: { 
    width: "100%", 
    height: 480, 
    borderRadius: 36, 
    elevation: 12, 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 12 }, 
    shadowOpacity: 0.15, 
    shadowRadius: 24, 
    borderWidth: 1, 
    borderColor: c.border,
    overflow: "hidden" 
  },
  cardFrontPremium: { backgroundColor: c.surface },
  cardBackPremium: { backgroundColor: isDark ? "rgba(79, 70, 229, 0.15)" : c.primaryLight, borderColor: c.primary + "40" },
  premiumCardInner: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 },
  cardTag: { 
    position: "absolute", 
    top: 30, 
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: c.primaryLight, 
    paddingHorizontal: 12, 
    paddingVertical: 6, 
    borderRadius: 20 
  },
  cardTagText: { fontSize: 10, fontWeight: "900", color: c.primary, letterSpacing: 1 },
  premiumCardMain: { fontSize: 52, fontWeight: "900", color: c.text, textAlign: "center" },
  premiumCardSub: { fontSize: 24, fontWeight: "700", color: c.primary, marginTop: 12 },
  premiumCardMeaning: { fontSize: 36, fontWeight: "800", color: c.text, textAlign: "center", lineHeight: 48 },
  premiumCardSecondary: { marginTop: 20, paddingHorizontal: 15, paddingVertical: 8, backgroundColor: "rgba(0,0,0,0.05)", borderRadius: 12 },
  premiumCardSecondaryText: { fontSize: 14, fontWeight: "700", color: c.textSecondary },
  premiumTapHint: { position: "absolute", bottom: 30, flexDirection: "row", alignItems: "center", gap: 8 },
  premiumTapHintText: { fontSize: 11, fontWeight: "800", color: c.textMuted, letterSpacing: 1 },
  
  premiumProgress: { width: 100, height: 4, backgroundColor: "rgba(255,255,255,0.2)", borderRadius: 2, marginTop: 6, overflow: "hidden" },
  premiumProgressBar: { height: "100%", backgroundColor: "#fff" },

  premiumNav: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 35, minHeight: 60 },
  premiumNavBtn: { width: 56, height: 56, borderRadius: 20, backgroundColor: c.surface, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: c.border },
  disabledBtn: { opacity: 0.3 },
  premiumNextBtn: { flex: 1, height: 56, borderRadius: 20, backgroundColor: c.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, marginLeft: 12 },
  premiumNextBtnText: { color: "#fff", fontSize: 15, fontWeight: "900", letterSpacing: 1 },
  tracingContainer: { flex: 1, flexDirection: "row", gap: 12 },
  tracingBtn: { flex: 1, height: 56, borderRadius: 20, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  wrongBtn: { backgroundColor: c.danger },
  correctBtn: { backgroundColor: c.success },
  tracingBtnText: { color: "#fff", fontSize: 14, fontWeight: "900", letterSpacing: 1 },

  speechBtn: { marginTop: 15, width: 48, height: 48, borderRadius: 24, backgroundColor: c.primaryLight, alignItems: "center", justifyContent: "center" },
  
  shuffleToggle: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(0,0,0,0.15)", paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10, marginTop: 4 },
  shuffleToggleText: { fontSize: 9, fontWeight: "900", color: "#fff", letterSpacing: 0.5 },

  polaBoxMini: { backgroundColor: c.primaryLight, paddingHorizontal: 15, paddingVertical: 8, borderRadius: 12, marginTop: 15 },
  polaTextMini: { fontSize: 15, fontWeight: "800", color: c.primary },

  grammarFlashDetail: { width: "100%", marginTop: 25, paddingHorizontal: 10 },
  grammarFlashLabel: { fontSize: 10, fontWeight: "900", color: c.textMuted, marginBottom: 12, letterSpacing: 1 },
  grammarFlashEx: { backgroundColor: "rgba(0,0,0,0.03)", padding: 15, borderRadius: 16, marginBottom: 10 },
  grammarFlashExJp: { fontSize: 16, fontWeight: "700", color: c.text, marginBottom: 4 },
  grammarFlashExId: { fontSize: 13, color: c.textSecondary, fontStyle: "italic" },

  // N5 Custom Hero
  n5Hero: { marginBottom: 25, borderRadius: 24, overflow: "hidden", backgroundColor: c.primary },
  n5HeroGrad: { padding: 20 },
  n5HeroRow: { flexDirection: "row", alignItems: "center", gap: 15, marginBottom: 20 },
  n5HeroIcon: { width: 60, height: 60, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },
  n5HeroText: { flex: 1 },
  n5HeroTitle: { fontSize: 20, fontWeight: "900", color: "#fff" },
  n5HeroSub: { fontSize: 12, color: "rgba(255,255,255,0.7)", fontWeight: "600", marginTop: 4 },
  n5HeroStats: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(0,0,0,0.15)", borderRadius: 16, padding: 12 },
  n5StatItem: { flex: 1, alignItems: "center" },
  n5StatVal: { fontSize: 14, fontWeight: "900", color: "#fff" },
  n5StatLabel: { fontSize: 9, fontWeight: "700", color: "rgba(255,255,255,0.5)", textTransform: "uppercase", marginTop: 2 },
  n5StatDivider: { width: 1, height: 20, backgroundColor: "rgba(255,255,255,0.1)" },
  n5ResumeBtn: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#fff", paddingHorizontal: 15, paddingVertical: 8, borderRadius: 12, marginLeft: 10 },
  n5ResumeText: { fontSize: 12, fontWeight: "900", color: c.primary },

  // Tool Styles
  addToCourseBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, paddingVertical: 18, borderRadius: 20, borderWidth: 2, borderColor: c.primaryLight, marginTop: 20 },
  addToCourseBtnText: { fontSize: 15, fontWeight: "800", color: c.primary },

  // Modal Styles
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalContent: { backgroundColor: c.surface, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 25, maxHeight: "80%" },
  modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: "900", color: c.text },
  modalLabel: { fontSize: 11, fontWeight: "900", color: c.textMuted, textTransform: "uppercase", letterSpacing: 1, marginTop: 15, marginBottom: 10 },
  pathPicker: { flexDirection: "row", marginBottom: 10 },
  pathChip: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, backgroundColor: c.background, marginRight: 10, borderWidth: 1, borderColor: c.border },
  pathChipActive: { backgroundColor: c.primary, borderColor: c.primary },
  pathChipText: { fontSize: 13, fontWeight: "700", color: c.textSecondary },
  pathChipTextActive: { color: "#fff" },
  lessonPicker: { maxHeight: 200, marginBottom: 20 },
  lessonPickItem: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: c.border },
  lessonPickItemActive: { borderBottomColor: c.primary },
  lessonPickText: { fontSize: 14, fontWeight: "600", color: c.text },
  lessonPickTextActive: { color: c.primary, fontWeight: "800" },
  saveConfirmBtn: { backgroundColor: c.primary, paddingVertical: 18, borderRadius: 20, alignItems: "center", justifyContent: "center", marginTop: 10 },
  saveConfirmText: { color: "#fff", fontSize: 15, fontWeight: "900", letterSpacing: 1 },

  // Existing styles...
  // Detail Styles
  detailHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 20, backgroundColor: c.background },
  detailBackBtn: { width: 44, height: 44, borderRadius: 12, backgroundColor: c.surface, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: c.border },
  detailHeaderTitle: { fontSize: 18, fontWeight: "900", color: c.text },
  detailContent: { padding: 25 },
  detailHero: { alignItems: "center", marginBottom: 30, paddingBottom: 30, borderBottomWidth: 1, borderBottomColor: c.border },
  heroMain: { fontSize: 48, fontWeight: "900", color: c.text, textAlign: "center" },
  heroSub: { fontSize: 22, fontWeight: "800", color: c.primary, marginTop: 10, textAlign: "center" },
  
  detailSection: { marginBottom: 25 },
  sectionHead: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 },
  sectionLabel: { fontSize: 12, fontWeight: "900", color: c.textMuted, letterSpacing: 1 },
  sectionText: { fontSize: 16, color: c.text, lineHeight: 26, fontWeight: "500" },
  polaBox: { backgroundColor: c.primaryLight, padding: 20, borderRadius: 20 },
  polaText: { fontSize: 18, fontWeight: "800", color: c.primary },
  exampleCard: { backgroundColor: c.surface, padding: 18, borderRadius: 20, marginBottom: 12, borderWidth: 1, borderColor: c.border },
  exJp: { fontSize: 18, fontWeight: "700", color: c.text, marginBottom: 6 },
  exId: { fontSize: 15, color: c.textSecondary, fontStyle: "italic" },

  meanGrid: { gap: 15, marginBottom: 30 },
  meanRow: { backgroundColor: c.surface, padding: 18, borderRadius: 20, borderWidth: 1, borderColor: c.border },
  meanLabel: { fontSize: 10, fontWeight: "900", color: c.primary, marginBottom: 5 },
  meanVal: { fontSize: 18, fontWeight: "800", color: c.text },
  speakBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 12, backgroundColor: c.primary, paddingVertical: 20, borderRadius: 24 },
  speakBtnText: { color: "#fff", fontWeight: "900", fontSize: 16 },

  tokenRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center' }
});
